### ISSUE TITLE
RFC: augur subsample command

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#635]
A common use case is versatile sub-sampling of datasets to suit a particular research question. The current best example of this is the (wonderful) SARS-CoV-2 pipeline which leverages a [augur filter rule](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L352-L403), a [script to calculate priorities](https://github.com/nextstrain/ncov/blob/master/scripts/priorities.py) and [snakemake](https://github.com/nextstrain/ncov/blob/21e8b4297f3725cae0fe6e41b800ac96d9798a28/workflow/snakemake_rules/main_workflow.smk#L275) [wizardry](https://github.com/nextstrain/ncov/blob/21e8b4297f3725cae0fe6e41b800ac96d9798a28/workflow/snakemake_rules/main_workflow.smk#L432) to allow versatile, declarative subsampling schemes to be [simply and intuitively defined](https://github.com/nextstrain/ncov/blob/master/my_profiles/example_advanced_customization/builds.yaml#L95-L134).

This allows a simple-to-reason-with YAML file to result in a very bespoke subsampling scheme:
![image](https://user-images.githubusercontent.com/8350992/100815202-457e7e80-34a8-11eb-88d9-331108087513.png)

The question arises: how do we do this for a different pathogen?

As the SARS-CoV-2 example leverages snakemake, one solution would be to abstract that logic into a importable snakemake rule. The alternative approach would be a new augur command `augur subsample` which takes a YAML file declaring the desired subsampling settings. Learning from our work on nCoV, this would essentially replace the snakemake-controlled `augur filter` commands with a single `augur subsample` command. The yaml file would look similar / identical to the [current snakemake implementation](https://github.com/nextstrain/ncov/blob/master/my_profiles/example_advanced_customization/builds.yaml#L95-L134). The subcommand would leverage the functions used by `augur filter` as well as the priorities script from nCoV.

Thoughts?

**Examples**  

`subsampling.yaml`:
```yaml
schemes:
  switzerland:
    # Focal samples for country
    country:
      group_by: "division year month"
      max_sequences: 1500
      exclude: "--exclude-where 'country!={country}'"
    # Contextual samples from country's region
    region:
      group_by: "country year month"
      seq_per_group: 20
      exclude: "--exclude-where 'country={country}' 'region!={region}'"
      priorities:
        type: "proximity"
        focus: "country"
    # Contextual samples from the rest of the world,
    # excluding the current region to avoid resampling.
    global:
      group_by: "country year month"
      seq_per_group: 10
      exclude: "--exclude-where 'region={region}'"
      priorities:
        type: "proximity"
        focus: "country"
```

```
augur subsample --include <TXT> --sequences <FASTA> \
    --metadata <TSV> --schemes <YAML> --output <FASTA>
```
